### ISSUE TITLE
Should `RanefInfo` and `CoefByGroup` move to MixedModels pre v4.0.0 release?

### ISSUE THREAD

**Issue by dmbates** [palday/MixedModelsMakie.jl#18]
The `RanefInfo` and `CoefByGroup` structs and their constructors could be added to the MixedModels package if they were thought to be of use beyond this package.

If so we should consider doing so before MixedModels v4.0.0

**Comment by dmbates** [comment]
The question is answered for `CoefByGroup` because type that has been eliminated from this package.  Still unsure about `RanefInfo`

**Comment by palday** [comment]
We can make the move non-breaking, so I wouldn't worry about rushing this. On the MixedModels end, adding features isn't breaking; for this package, it's non breaking because we can just import the functionality from MixedModels and re-export as necessary. The only restriction is the resulting change in `compat` bound for the dependency.
